---
- name: Install OpenVPN
  hosts: all
  remote_user: root
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python
  roles:
    - fail2ban
  vars_files:
    - defaults/main.yml
    
    